# Generated by Django 5.0.7 on 2024-07-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vulnerabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vul', models.CharField(max_length=50)),
                ('fixeada', models.BooleanField(default=False)),
                ('date_fixeada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
