# Generated by Django 5.0.7 on 2024-07-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuln', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vulnerabilities',
            old_name='id_vul',
            new_name='vul_id',
        ),
    ]
